### ISSUE TITLE
500 Error No matching Method/Function [renderCSRFTokens] for call with named arguments found

### ISSUE THREAD

**Issue by GarethMan** [MSU-NatSci/MuraCMS#1]
Hi, I'm migrating a mura 6 site to 7.1 and I have most of it working but some pages are returning the following error.

I can't seem to find any info on this online. The site was previously on adobe coldfusion but the new version is on lucee.

Thanks
Gareth

500 Error
No matching Method/Function [renderCSRFTokens] for call with named arguments found
Code:0
Type:expression
lucee.runtime.exp.ExpressionException: No matching Method/Function [renderCSRFTokens] for call with named arguments found 
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:879)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at content.datacollection.datacollectionmanager_cfc$cf.udfCall(/mura/content/dataCollection/dataCollectionManager.cfc:323)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:684)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1911)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1747)
	at sites.apse.includes.display_objects.datacollection.index_cfm$cf$10.call(/muraWRM/sites/apse/includes/display_objects/datacollection/index.cfm:90)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1034)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:926)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:907)
	at content.contentrenderer_cfc$cf.udfCall6(/mura/content/contentRenderer.cfc:1620)
	at content.contentrenderer_cfc$cf.udfCall(/mura/content/contentRenderer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:802)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at cfobject_cfc$cf.udfCall3(/mura/cfobject.cfc:229)
	at cfobject_cfc$cf.udfCall(/mura/cfobject.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1930)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at murascope_cfc$cf.udfCall1(/mura/MuraScope.cfc:103)
	at murascope_cfc$cf.udfCall(/mura/MuraScope.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:684)
	at lucee.runtime.ComponentImpl.onMissingMethod(ComponentImpl.java:611)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:574)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1930)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at core.modules.v1.form.index_cfm$cf$z.call(/muraWRM/core/modules/v1/form/index.cfm:168)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1034)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:926)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:907)
	at content.contentrenderer_cfc$cf.udfCall6(/mura/content/contentRenderer.cfc:1620)
	at content.contentrenderer_cfc$cf.udfCall(/mura/content/contentRenderer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:785)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1747)
	at content.contentrenderer_cfc$cf.udfCall6(/mura/content/contentRenderer.cfc:1520)
	at content.contentrenderer_cfc$cf.udfCall(/mura/content/contentRenderer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1930)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at content.contentrendererutility_cfc$cf.udfCall4(/mura/content/contentRendererUtility.cfc:1286)
	at content.contentrendererutility_cfc$cf.udfCall(/mura/content/contentRendererUtility.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1930)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at content.contentrenderer_cfc$cf.udfCall8(/mura/content/contentRenderer.cfc:2369)
	at content.contentrenderer_cfc$cf.udfCall(/mura/content/contentRenderer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1930)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at content.contentrendererutility_cfc$cf.udfCall4(/mura/content/contentRendererUtility.cfc:1508)
	at content.contentrendererutility_cfc$cf.udfCall(/mura/content/contentRendererUtility.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1930)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at content.contentrenderer_cfc$cf.udfCall8(/mura/content/contentRenderer.cfc:2396)
	at content.contentrenderer_cfc$cf.udfCall(/mura/content/contentRenderer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:802)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at cfobject_cfc$cf.udfCall3(/mura/cfobject.cfc:229)
	at cfobject_cfc$cf.udfCall(/mura/cfobject.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1930)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at murascope_cfc$cf.udfCall1(/mura/MuraScope.cfc:103)
	at murascope_cfc$cf.udfCall(/mura/MuraScope.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:684)
	at lucee.runtime.ComponentImpl.onMissingMethod(ComponentImpl.java:611)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:574)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1911)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1747)
	at sites.apse.themes.u6bootstrap.templates.inc.two_column_sr_cfm$cf$y.call(/muraWRM/sites/apse/themes/U6Bootstrap/templates/inc/two_column_SR.cfm:52)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1034)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:926)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:907)
	at sites.apse.themes.u6bootstrap.templates.two_column_sr_cfm$cf$x.call(/muraWRM/sites/apse/themes/U6Bootstrap/templates/two_column_SR.cfm:2)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1034)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:926)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:907)
	at translator.standardhtmltranslator_cfc$cf.udfCall(/mura/Translator/standardHTMLTranslator.cfc:98)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1930)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/mura/plugin/pluginStandardEventWrapper.cfc:137)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:684)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1911)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1747)
	at handler.standardeventshandler_cfc$cf.udfCall1(/mura/Handler/standardEventsHandler.cfc:87)
	at handler.standardeventshandler_cfc$cf.udfCall(/mura/Handler/standardEventsHandler.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1925)
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:209)
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:186)
	at utility_cfc$cf.udfCall7(/mura/utility.cfc:1372)
	at utility_cfc$cf.udfCall(/mura/utility.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1930)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/mura/plugin/pluginStandardEventWrapper.cfc:87)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:684)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1911)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1747)
	at handler.standardeventshandler_cfc$cf.udfCall3(/mura/Handler/standardEventsHandler.cfc:422)
	at handler.standardeventshandler_cfc$cf.udfCall(/mura/Handler/standardEventsHandler.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1925)
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:209)
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:186)
	at utility_cfc$cf.udfCall7(/mura/utility.cfc:1372)
	at utility_cfc$cf.udfCall(/mura/utility.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1930)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at plugin.pluginstandardeventwrapper_cfc$cf.udfCall(/mura/plugin/pluginStandardEventWrapper.cfc:87)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:684)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1911)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1747)
	at content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:845)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:785)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1747)
	at content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:259)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:785)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1747)
	at content.contentserver_cfc$cf.udfCall1(/mura/content/contentServer.cfc:345)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:685)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1930)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:866)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1766)
	at content.contentserver_cfc$cf.udfCall2(/mura/content/contentServer.cfc:716)
	at content.contentserver_cfc$cf.udfCall(/mura/content/contentServer.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:684)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:572)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1911)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1747)
	at index_cfm$cf.call(/index.cfm:43)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1034)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:926)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:217)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2460)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2450)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2421)
	at lucee.runtime.engine.Request.exe(Request.java:45)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1179)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1125)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:433)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by GarethMan** [comment]
I believe this happens only on pages with forms on. I'm trying to create a page with a new test form but the previous dev of the site did something to hide the top bar so I cannot access inline editing at the moment.
